#!/bin/bash
# when formatting partitions, use GPT and add an 'EFI System' 100M partition


# pacstrap
pacstrap -i /mnt base base-devel zsh git net-tools networkmanager gummiboot xorg-xserver xorg-xinit xorg-utils xorg-server-utils rxvt-unicode i3 dmenu autocutsel gvim cmake
genfstab -U /mnt > /mnt/etc/fstab
cat /mnt/etc/fstab

arch-chroot /mnt /bin/zsh

# locale
nano /etc/locale.gen # uncomment de_DE UTF-8
locale-gen
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo -e "KEYMAP=de-latin1\nFONT=lat9w-16" > /etc/vconsole.conf
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc --utc

# hostname
echo myhostname > /etc/hostname
nano /etc/hosts # add 'myhostname' to end of each line

# setup boot
gummiboot install
gummiboot update

# create user
useradd NAME -m -g users -G wheel -s /bin/zsh 

# dotfiles 'n stuff
  # change user to created one
  # setup dotfiles
  # setup paranoid_link
  # edit files for paranoid stuff
mkinitcpio -p linux
cat <<_EOF_ > /boot/loader/entries/arch.conf
title       Arch Linux
linux       /vmlinuz-linux
initrd      /initramfs-linux.img
options     cryptdevice=/dev/sda3:system root=/dev/mapper/system
_EOF_

nano /boot/loader/entries/arch.conf # adapt /dev/sdXX

cat <<_EOF_ > /boot/loader/loader.conf
default arch
timeout 0
_EOF_

pacman -S python3
pacman -S python2
pacman -S arandr
pacman -S ttf-dejavu
pacman -S opera
pacman -S wget

# yaourt
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
makepkg -si
cd ..
rm -r package-query package-query.tar.gz
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvzf yaourt.tar.gz
cd yaourt
makepkg -si
cd ..
rm -r yaourt yaourt.tar.gz

yaourt -S vivaldi
pacman -S ffmpeg
pacman -S vlc
yaourt -S livestreamer
pacman -S mumble
pacman -S pulseaudio
pacman -S pavucontrol

# enable multilib in /etc/pacman.conf
pacman -Syu
yaourt -S steam
pacman -S evince
pacman -S feh
pacman -S imagemagick
yaourt -S catalyst
pacman -S thunderbird
pacman -S skype
pacman -S pidgin pidgin-otr
pacman -S openssh
pacman -S htop iotop
pacman -S unzip
pacman -S nmap
pacman -S mlocate
pacman -S gedit
