#!/bin/bash

UUID="30a65847-0e31-4c1c-85b1-3f6c9f9ff4e1"
DEVICE="/dev/disk/by-uuid/$UUID"

run_hook() {
  if [ ! -e $DEVICE ]
      then
          echo -n No Keyfiles found -- please insert USB-Drive and press return...
          read
  fi

  if [ ! -e $DEVICE ]
      then
          echo -n pre-poweroff
          read
          poweroff
    echo -n post-poweroff, pre-shutdown -P
    read
    shutdown -P now "No Keyfile found"
    echo -n post-shutdown, fucked up
    read
  fi

  echo "modprobe"
  modprobe -a aesni_intel crypto_simd glue_helper dm_crypt dm_mod cryptd pcrypt
  echo "modprobe done"
  lsmod | grep crypt
  lsmod | grep aes
  cryptsetup -T 3 open $DEVICE keys
  mkdir /keys
  mount /dev/mapper/keys /keys
  #ln -s /keys/keyfile_lvm /crypto_keyfile.bin
  echo "opening lvm..."
  cryptsetup open -d /keys/keyfile_lvm /dev/nvme1n1p2 lvm
  echo "lvm opened"
  echo "opening lvm2..."
  cryptsetup open -d /keys/keyfile_lvm2_512G /dev/nvme0n1p1 lvm2
  echo "lvm2 opened"
}

run_latehook() {
  umount /keys
  cryptsetup close keys
  rm -r /keys
}
