#!/bin/bash

UUID="30a65847-0e31-4c1c-85b1-3f6c9f9ff4e1"
DEVICE="/dev/disk/by-uuid/$UUID"

run_hook() {
  if [ ! -e $DEVICE ]
      then
          echo -n No Keyfiles found -- please insert USB-Drive and press return...
          read
  fi

  if [ ! -e $DEVICE ]
      then
          echo -n pre-poweroff
          read
          poweroff
    echo -n post-poweroff, pre-shutdown -P
    read
    shutdown -P now "No Keyfile found"
    echo -n post-shutdown, fucked up
    read
  fi

  cryptsetup -T 3 open $DEVICE keys
  mkdir /keys
  mount /dev/mapper/keys /keys
  ln -s /keys/keyfile_system /crypto_keyfile.bin
}

run_latehook() {
  cryptsetup open -d /keys/keyfile_swap /dev/nvme0n1p2 swap
  umount /keys
  cryptsetup close keys
  rm -r /keys
}

