#!/bin/bash -ex

if [ "$EUID" -ne 0 ]; then
  echo "Run as root"
  exit
fi

if [ ! -x "`which mprime`" ]; then
  echo "Please install mprime"
  exit 1
fi

if ! mountpoint -q /mnt || [ ! -f /mnt/arch/x86_64/airootfs.sfs ]; then
  echo "Please mount the arch-bootstrap partition at /mnt"
  exit 2
fi

if ! mountpoint -q /boot; then
  echo "Please mount the boot partition at /boot"
  exit 3
fi


unsquashfs /mnt/arch/x86_64/airootfs.sfs

err=0
for lib in $(ldd $(which mprime) | grep '=>' | sed -r 's/.*?=> (.*?) \(.*/\1/'); do
  if [ ! -f "squashfs-root$lib" ]; then
    echo "Library $lib required by mprime but not available on live system"
    err=1
  fi
done
if [ "$err" = 1 ]; then
  exit
fi

cp `which mprime` "squashfs-root`which mprime`"
cp $(eval echo ~`logname`)/dotfiles/xorg/{.xinitrc,.Xresources} squashfs-root/root/

./squashfs-root/bin/arch-chroot squashfs-root /bin/bash << EOF
export TERM=xterm-256color
sed -i 's/CheckSpace/#CheckSpace/' /etc/pacman.conf
pacman-key --init
pacman-key --populate archlinux
pacman-key --refresh-keys
pacman -Syu --noconfirm
pacman -S --noconfirm xorg-server xorg-xinit xorg-apps xf86-video-intel gparted
# fix compinit directories
chown -R root:root /usr/share/zsh
chmod -R 755 /usr/share/zsh
wget https://neo-layout.org/svn/linux/console/neo.map
mkdir -p /usr/share/kbd/keymaps/i386/neo
mv neo.map /usr/share/kbd/keymaps/i386/neo/
localectl set-keymap --no-convert de neo
mkinitcpio -p linux
LANG=C pacman -Sl | awk '/\[installed\]$/ {print $1 "/" $2 "-" $3}' > /pkglist.txt
yes | pacman -Scc
exit
EOF
cp squashfs-root/boot/vmlinuz-linux /boot/arch/boot/x86_64/vmlinuz
cp squashfs-root/boot/initramfs-linux.img /boot/arch/boot/x86_64/archiso.img
mv squashfs-root/pkglist.txt /mnt/arch/pkglist.x86_64.txt
mksquashfs squashfs-root airootfs.sys
mv airootfs.sys /mnt/arch/x86_64/airootfs.sfs
md5sum /mnt/arch/x86_64/airootfs.sfs > /mnt/arch/x86_64/airootfs.md5
rm -r squashfs-root
sync
