#!/bin/bash -eux
set -o pipefail

if [ "$EUID" -ne 0 ]; then
  echo "Run as root"
  exit
fi

if ! mountpoint -q /mnt || [ ! -f /mnt/archiso/x86_64/airootfs.sfs ]; then
  echo "Please mount the boot partition at /mnt"
  exit 2
fi

unsquashfs /mnt/archiso/x86_64/airootfs.sfs

install_binary_with_libraries() {
  if [ ! -x "`which $1`" ]; then
    prog=$2
    if [ "$prog" = "" ]; then
      prog=$1
    fi
    echo "Binary \`$1\` not found, please install package \`$prog\`"
    exit 1
  fi

  err=0
  for lib in $(ldd $(which $1) | grep '=>' | sed -r 's/.*?=> (.*?) \(.*/\1/'); do
    if [ "$lib" = "linux-vdso.so.1" ]; then
      continue
    fi
    if [ ! -f "squashfs-root$lib" ]; then
      echo "Library $lib required by $1 but not available on live system, copying..."
      cp "$lib" "squashfs-root$lib" || (echo "copying failed"; err=1)
    fi
  done
  if [ "$err" = 1 ]; then
    exit
  fi

  cp `which $1` "squashfs-root`which $1`"
}

install_binary_with_libraries mprime
install_binary_with_libraries sedutil-cli sedutil
install_binary_with_libraries linuxpba sedutil

cp $(eval echo ~`logname`)/dotfiles/xorg/{.xinitrc,.Xresources} squashfs-root/root/

./squashfs-root/bin/arch-chroot squashfs-root /bin/bash << "EOF" || true
set -euo pipefail
export TERM=xterm-256color
mkdir -p /root/.i3/log
sed -i 's/^CheckSpace/#CheckSpace/' /etc/pacman.conf
pacman-key --init
pacman-key --populate archlinux
pacman-key --refresh-keys
pacman -Sy --noconfirm
pacman -S --noconfirm archlinux-keyring
pacman -Syu --noconfirm
pacman -S --noconfirm --needed base-devel xorg-server xorg-xinit xorg-apps xf86-video-intel gparted kdiskmark rxvt-unicode wget rustup git curl
rustup install stable nightly
# fix compinit directories
chown -R root:root /usr/share/zsh
chmod -R 755 /usr/share/zsh
grep loadkeys /root/.zshrc || echo loadkeys neo >> /root/.zshrc
echo KEYMAP=neo > /etc/vconsole.conf
echo FONT=lat9w-16 >> /etc/vconsole.conf
mkinitcpio -p linux
LANG=C pacman -Sl | awk '/\[installed\]$/ {print $1 "/" $2 "-" $3}' > /pkglist.txt
yes | pacman -Scc
exit
EOF
cp squashfs-root/boot/vmlinuz-linux /mnt/archiso/boot/x86_64/vmlinuz-linux
cp squashfs-root/boot/initramfs-linux.img /mnt/archiso/boot/x86_64/initramfs-linux.img
mv squashfs-root/pkglist.txt /mnt/archiso/pkglist.x86_64.txt
mksquashfs squashfs-root airootfs.sys
mv airootfs.sys /mnt/archiso/x86_64/airootfs.sfs
sha512sum /mnt/archiso/x86_64/airootfs.sfs > /mnt/archiso/x86_64/airootfs.sha512
rm -r squashfs-root
sync
