#!/bin/sh

ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.ideavimrc ~/.ideavimrc
mkdir ~/.vim/
mkdir ~/.vim/bundle/
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
sh ~/.vim/bundle/youcompleteme/install.sh --racer-completer --tern-completer
